// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/api/roadmap.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roadmap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Roadmap) Reset() {
	*x = Roadmap{}
	mi := &file_proto_api_roadmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Roadmap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roadmap) ProtoMessage() {}

func (x *Roadmap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_api_roadmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roadmap.ProtoReflect.Descriptor instead.
func (*Roadmap) Descriptor() ([]byte, []int) {
	return file_proto_api_roadmap_proto_rawDescGZIP(), []int{0}
}

func (x *Roadmap) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Roadmap) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Roadmap) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Roadmap) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Roadmap) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Roadmap) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Roadmap) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_api_roadmap_proto protoreflect.FileDescriptor

const file_proto_api_roadmap_proto_rawDesc = "" +
	"\n" +
	"\x17proto/api/roadmap.proto\x12\aroadmap\"\xc0\x01\n" +
	"\aRoadmap\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06statusB\x10Z\x0einternal/modelb\x06proto3"

var (
	file_proto_api_roadmap_proto_rawDescOnce sync.Once
	file_proto_api_roadmap_proto_rawDescData []byte
)

func file_proto_api_roadmap_proto_rawDescGZIP() []byte {
	file_proto_api_roadmap_proto_rawDescOnce.Do(func() {
		file_proto_api_roadmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_api_roadmap_proto_rawDesc), len(file_proto_api_roadmap_proto_rawDesc)))
	})
	return file_proto_api_roadmap_proto_rawDescData
}

var file_proto_api_roadmap_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_api_roadmap_proto_goTypes = []any{
	(*Roadmap)(nil), // 0: roadmap.Roadmap
}
var file_proto_api_roadmap_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_api_roadmap_proto_init() }
func file_proto_api_roadmap_proto_init() {
	if File_proto_api_roadmap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_api_roadmap_proto_rawDesc), len(file_proto_api_roadmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_api_roadmap_proto_goTypes,
		DependencyIndexes: file_proto_api_roadmap_proto_depIdxs,
		MessageInfos:      file_proto_api_roadmap_proto_msgTypes,
	}.Build()
	File_proto_api_roadmap_proto = out.File
	file_proto_api_roadmap_proto_goTypes = nil
	file_proto_api_roadmap_proto_depIdxs = nil
}
